XDK: Fix the 64-bits build with clang.
The `cctest` build is failing on x86-64 because several places use int's
instead of size_t's to store the return value of std::string::find().

clang is pickier than GCC, and fails with errors such as:
../test/cctest/test-heap-profiler.cc:2825:26: error: implicit conversion loses integer precision: 'size_type' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]

Just use `auto` instead of `int` to fix it.